- CONTRIBUTING.md
- performance.md
Links the existing images to the handbook and adds documentation about how to add media in the future.
See: https://meta.trac.wordpress.org/ticket/5247#comment:5
> Change assets to point to Make Handbook directly.

- security.md
There was a dead link to a guide which was moved to a new URL
> fixed dead link as the linked guide was moved

- server-environment.md
slack conversation: https://wordpress.slack.com/archives/C3D6T7F8Q/p1594925003328900
ext/sodium is available in PHP core as of PHP 7.2. As far as I can tell from https://github.com/WordPress/WordPress/commit/cb01bbf97b11c01a1dbe36e51cdb15b3eac99a0a, WordPress is expecting ext/sodium to be loaded and not ext/libsodium.
There could be some more nuance needed in this section to cover all the supported versions of PHP.
> recommend ext/sodium instead of ext/libsodium

- performance.md
Changed the recommendation of PHP 7.3 to 7.4 as most current version.
Also changed 7.1 to 7.2 as oldest version receiving security patches
> Lifted PHP Recommendation to 7.4

- security.md
Since SSL is obsolete i would recommend to change it to TLS / SSL. Keeping SSL in there allows users to still identify it as SSL is common.
> Changed "SSL" to "TLS / SSL"

- index.md
Currently the shortcode block needs to have links as a <a>-tag. Thats why we converted the current links in the content to <a>-tags
> added info box

- index.md
Updating via https://make.wordpress.org/hosting/2021/03/30/new-hosting-team-reps/
> team reps updated

- compatibility.md
- php-compatibility.md
First idea... we should check all versions and add the min/max.
#54
> WordPress compatibility table (PHP and MySQL)

- index.md
Related to https://github.com/WordPress/hosting-handbook/issues/32.
I took @javiercasares description version and tried to rewrite it a bit to make it shorter and easier to read. Let me know what you think 🙏🏻
> Adding "About the Hosting Team" section

- security.md
The update is based on the proposal of @javiercasares.
The idea was to provide more guidance on how to use auto updates (which are available since 5.5) but also give more guidance by linking the official documentation page.
> Updated the security page for auto updates

- get-involved.md
We added some information about the review process. Two or one approval needed.
> Github review process

- compatibility.md
- server-environment.md
Updated WordPress 6.0 / WordPress 6.1, PHP compatibility information and other versions
> WordPress 6.1 update (server requirements)

- server-environment.md
Nothing over at https://www.php.net/manual/en/intro.intl.php or https://www.php.net/manual/en/intl.setup.php mentions this extension being bundled in any PHP version; it wasn't in my PHP 8.1.4.
> Remove erroneous mention of intl being bundled

- server-environment.md
- Updated LiteSpeed Web Server
- Updates for WordPress 6.2 beta and PHP >= 7.4.
> Updates for WordPress 6.2 beta

- server-environment.md
- Updated the MariaDB 10.3 EOL.
- Updated WordPress 6.2 deprecated information and check for the latest one.
> Update MariaDB 10.3 EOL

- server-environment.md
Add shmop and move up intl to reflect current Site Health recommendations.
Add APCu as PHP’s ‘native’ alternative to memcached and redis.
> Update PHP extensions requirements and cache extensions

- tests.md
To have working tests, NodeJS 16 is required.
> Tests with NodeJS 16.x

- bin/handbook-manifest.json
- contributor-day.md
- team-projects.md
New page for the Tam Projects, different from the Contributor Day / volunteers onboarding.
> Separating Contributor and projects

- server-environment.md
Documentation about WordPress 6.4 and PHP 8.0, 8.1, and 8.2 exceptions.
> WordPress 6.4 exceptions

- team-reps.md
Changed Team Reps from 2023 to 2004, leaving only the new WordPress profiles.
Issue: Update the Team Reps
https://github.com/WordPress/hosting-handbook/issues/216
> Team Reps 2024 update

- team-reps.md
- Added `Hosting` Instead of `Hostin`
- Added `Nomination` Instead of `Nomitation`
**Fixes:** https://github.com/WordPress/hosting-handbook/issues/224
> Small Typo Correction in team-reps.md

- server-environment.md
Added minimum version of curl and OpenSSL for PHP 8.4
https://php.watch/versions/8.4#syntax-functionality-changes
> Add curl and OpenSSL minimum version for PHP 8.4

- compatibility.md
Re: [Hosting Handbook Issue #301](https://github.com/WordPress/hosting-handbook/issues/301)
Added a WordPress 6.8 line to the Handbook Compatibility page pending the release of WP 6.8 on 4/15/25.
The info matches the compatibility details in the [WP 6.8 Hosting Recommendations post draft ](https://docs.google.com/document/d/19k93IPaSGqKCXz2uzY7p2oAIY-CenyeSSCoNfCYFXRc/edit?tab=t.0#heading=h.kzl3cnpr4c1w)
Note: [This PR](https://github.com/WordPress/hosting-handbook/pull/302) updates this same page and does not include a 6.8 line. One of the PRs will need to be rebased prior to merging, depending on which is merged first.
> Added WP 6.8 to compatibility.md (Issue #301)

- compatibility.md
Updated the Handbook Compatibility page bottom changelog to reflect the addition of WP 6.8
Re: [GitHub Issue #304 ](https://github.com/WordPress/hosting-handbook/issues/304)
> Added WP 6.8 to compat page changelog re: #304

- team-reps.md
Re: https://github.com/WordPress/hosting-handbook/issues/321
Updated project lead info. Added team admins and past team reps/admins
> Update Team Reps Page 

- bin/handbook-manifest.json
- team-updates.md
I went ahead and added a how to on the Monthly Hosting Team posts. 
This should act like a first draft and to have all the links handy.
Addressing issue #341
> Adding a first version of Monthly Team Updates
