WordPress/hosting-handbook

CONTRIBUTING.md
After conversation in Slack: https://wordpress.slack.com/archives/C3D6T7F8Q/p1591175739108800
=> Changing review note to two required before merge

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, get-involved.md, index.md
Some formatting, links, capital letters and others on the actual published pages.
=> Formatting updates

bin/handbook-manifest.json
After renaming the environment.md file we also need to adapt the bin/handbook-manifest.json
=> Renamed the server-environment.md file also in the manifest.json

security.md
Reverts WordPress/hosting-handbook#15
=> Revert "New security page proposal"

server-environment.md
Updated from old #12. Open to new comments .
=> Updated Server requirements

CODE_OF_CONDUCT.md
Updated language in first and last paragraphs of code of conduct page.
=> updated language Code of Conduct

server-environment.md
Thank you for all the work in this repo! Enjoying going through it.
=> configuring -> configure

compatibility.md
Detailed the target to whom it is addressed and an info-tip to visit Core's Matrix.
=> target and info-tip

tests.md
Not for publishing. Requieres a revision and to add some more information on "Local Environment Recommendations" and "Travis, Circle or other CI".
=> New tests section

get-involved.md, index.md, performance.md, reliability.md, security.md, server-environment.md, tests.md
Adding infoboxes in all pages.
=> All infobox

get-involved.md, index.md, performance.md, reliability.md, security.md, server-environment.md, tests.md
- Added, at the end of each page, a new Changelog version with some dates and changes.
- Added the infobox at the end of each pages so all pages have the same information.
=> Changelog added

get-involved.md, index.md, performance.md, reliability.md, security.md, server-environment.md, tests.md
Updated some versions:
- Web servers versions: updated to maintained versions.
- PHP versions: updated to maintained versions, deteled PHP 7.2, added PHP 8.0, recommended PHP 7.4 (via Serve-Happy API)
- SQL versions: updated to maintained versions.
=> Server Environment updates

server-environment.md
- Software version update
- Minor versions deletion
- PHP min 7.3 (as [Core recommends](https://meta.trac.wordpress.org/changeset/10960))
- Reorder extensions alphabetically
- Improve extensions description
- Link external libraries
- Updated changelog
=> Versions and extensions update

performance.md
Based on Issue https://github.com/WordPress/hosting-handbook/issues/68
=> fixed interal links

get-involved.md, index.md, performance.md, reliability.md, security.md, server-environment.md, tests.md
Fixing the infoboxes without backslash
=> Fixing infoboxes

performance.md
Some first improvements... if you have new ones, please, add them to this PR.
=> Improving Performance page

server-environment.md
From https://core.trac.wordpress.org/ticket/55791
=> Delete MariaDB 10.2

CONTRIBUTING.md
During WCEU 2022 could not find any information on how to deal with the Markdown format or any of the different flavours of Markdown floating around. To make the entry level lower for new contributors the condensed answer is in this pr.
=> added basic info about the Markdown textformat

security.md
This commit should take care of #97. Thanks @BernardZijlstra
=> Added Responsible Disclosure

upgrading.md
=> Proposed Changes

server-environment.md
Added PHP extensions requirements and cache extensions.
=> PHP extensions

bin/handbook-manifest.json, upgrading.md
This page will show some ideas on how to upgrade an old WordPress to a new one.
=> "Upgrading" WordPress

index.md
Updating Jadon for Jessica. Thank you, a lot, Jadon, for all the work you've done for the Hosting Team. :)
=> Update the Team Reps 2023

server-environment.md
Add igbinary (see issue #170) and update descriptions for pcre and hash
=> Update recommended PHP extensions

server-environment.md
=> Added shmop PHP extension

bin/handbook-manifest.json
=> Improved manifest

compatibility.md
=> added Server requirements

team-reps.md
Added the following parts:
- How our voting process works
- Added link to slack channel
- Reworded for clarity
- Added third responsibility
- added note about Project Lead != Team Rep
=> Crixu team reps

bin/handbook-manifest.json, documentation.md
This new page will serve as a summary of the routine documentation review tasks that affect the Hosting Team throughout the project.
Generally, it relates to documentation associated with versions of WordPress, PHP, MySQL, MariaDB, Operating Systems, web servers, and so forth.
It also incorporates other pages or content that the Hosting Team is responsible for maintaining for various reasons, such as information on the Team Reps.
=> New documentation page

compatibility.md, live.md, server-environment.md, upgrading.md
This is the October maintenance for the documentation.
=> 2023-10 maintenance

compatibility.md, get-involved.md, server-environment.md, team-reps.md
- Everything is updated to WordPress 6.4.
- Some other minor fixes
=> WordPress 6.4 compatibility

learn-hosting.md
Partial Fixed: #221
I fixed two broken links but couldn't find one. If you have a solution, please let me know.
[Testing plugins for PHP 8](https://wordpress.tv/2023/05/19/testing-plugins-for-php-8/)
https://github.com/WordPress/hosting-handbook/blob/3184db7ce337f37c86d07a68250580125fedef13/learn-hosting.md?plain=1#L72
=> Fix: Broken Resource Links

compatibility.md, server-environment.md, tests.md, upgrading.md
- Page Upgraded: updated for WordPress 6.5
=> Updating for WordPress 6.5

compatibility.md, server-environment.md, upgrading.md
- Server Environment, updated for WordPress 6.6
- WordPress Compatibility, updated for WordPress 6.6
- Upgrading WordPress, updated for WordPress 6.6
=> Updates for WordPress 6.6

bin/handbook-manifest.json, sustainability.md
Result of WordCamp US Contributor Day. 
The goal was to create a handbook for hosting companies to offer a more sustainable hosting offering.
=> Add the initial version of the sustainability page

team-reps.md
Updated the team reps for 2025. Removed Javier and added Zunaid.
=> Updated Team Reps for 2025

learn-hosting.md
Replace invalid titles and broken URLs with valid titles and working URLs.
=> Fix Broken URL issues with new one.

tests.md
Close https://github.com/WordPress/hosting-handbook/issues/307
=> Fixed tip section not displaying correctly

server-environment.md, upgrading.md
=> Minor text corrections

team-projects.md
Changed "To work on this project yo will need" to "To work on this project you will need" in 3 places on team projects page
=> fixed typos team-projects.md

security.md
Update wordpress.org plugin link from HTTP to HTTPS.
=> Fix: Update URL to use https instead of http
